const MINUTE_MS = 60_000

export const RUN_START_TO_CLOSE_TIMEOUT_MS = 60 * MINUTE_MS

export const RUN_BUDGET_MS = RUN_START_TO_CLOSE_TIMEOUT_MS - 10 * MINUTE_MS

export const LEASE_GUARD_MS = RUN_START_TO_CLOSE_TIMEOUT_MS + 5 * MINUTE_MS
